# -*- coding: utf-8 -*-
"""data30_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k88ZdzOD3IyZHBXxqI8e4CC38JrZWMxF
"""

!pip install git+https://github.com/ssut/py-hanspell.git

!pip install git+https://github.com/haven-jeon/PyKoSpacing.git

import pandas as pd

# 전처리된 CSV 로드
df = pd.read_csv("preprocessed_smishing_final.csv")

# 제거 대상 키워드 목록
keywords = [
    "택배", "카드 신청", "반품", "보관", "수거", "반송",
    "현관", "발급", "우편물", "우편함", "우편", r"(배송\s?예정|배달\s?예정)",
    "배송", "운송장"
]

# 각 키워드에 대해 "국제|국외"가 포함되지 않은 경우만 제거
for keyword in keywords:
    condition = df["clean_df"].str.contains(keyword, na=False) & ~df["clean_df"].str.contains("국제|국외", na=False)
    df = df[~condition].copy()

#중복제거
df = df.drop_duplicates(subset=["clean_df"]).copy()

# 저장
df.to_csv("keyword_smishing.csv", index=False, encoding="utf-8-sig")
# print("전처리 완료: keyword_smishing.csv 저장됨")

import pandas as pd
import re
from pykospacing import Spacing
from hanspell import spell_checker
from tqdm import tqdm
import csv

tqdm.pandas()
spacing = Spacing()

# 데이터 불러오기 (앞 300개만 샘플링)
df = pd.read_csv("keyword_smishing.csv")

# 맞춤법 교정 함수
def safe_spell_check(text):
    try:
        if isinstance(text, str) and 1 < len(text) <= 500:
            result = spell_checker.check(text)
            if hasattr(result, 'checked'):
                return result.checked
    except:
        pass
    return text

# 전처리 함수
def preprocess_text(text):
    if not isinstance(text, str):
        return text

    text = text.replace("ifg@", "")

    # URL(http/https/www 또는 축약 주소 포함)
    url_pattern = r"(https?://|http?://|www\.)[^\s]+|\b(?:[a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}(?:/[^\s]*)?"
    text = re.sub(url_pattern, "URL", text)

    # 날짜 마스킹
    text = re.sub(r"\d{4}년\s?\d{1,2}월\s?\d{1,2}일", "DATE", text)
    text = re.sub(r"\d{1,2}월\s?\d{1,2}일?", "DATE", text)
    text = re.sub(r"\d{1,4}년\s?\d{1,2}월", "DATE", text)
    text = re.sub(r"\d{1,2}/\d{1,2}\(.\)", "DATE", text)
    text = re.sub(r"\d{1,2}/\d{1,2}\(\w+\)", "DATE", text)
    text = re.sub(r"\d{1,2}일", "DATE", text)
    text = re.sub(r"\d{1,4}년", "DATE", text)
    text = re.sub(r"\d{1,2}월", "DATE", text)


    # 시간 마스킹
    text = re.sub(r"\d{2}:\d{2}", "TIME", text)
    text = re.sub(r"\d{1,2}시간", "TIME", text)
    text = re.sub(r"\d{1,2}시", "TIME", text)
    text = re.sub(r"\d{1,2}시\s*[\-~]\s*\d{1,2}시", "TIME", text)

    # 로또 마스킹
    text = re.sub(r"L\*TT\*", "로또", text)

    # 공백 압축
    text = re.sub(r"\s{2,}", " ", text)

    # 숫자/전화번호/마스킹 → NUM
    text = re.sub(r"[\*\d,\-_\s]{6,}", "NUM", text)
    text = re.sub(r"\d+\.\d+", "NUM", text)  # 99.9 → NUM 소숫점 자리
    text = re.sub(r"\d+", "NUM", text)


    # 기관 키워드 복원
    text = re.sub(r"\b(정부|민원|교통|경찰청|경찰)NUM\b", r"\g<1>24", text)

    # 특수문자 제거
    text = re.sub(r"[^가-힣a-zA-Z0-9\s]", "", text)

    # 띄어쓰기
    text = spacing(text)

    # 맞춤법
    text = safe_spell_check(text)

    return text

# 전처리 적용
df["clean_df"] = df["SMS"].progress_apply(preprocess_text)

# 중복 제거
df = df.drop_duplicates(subset=["clean_df"]).copy()

# 저장 (쉼표로 열 분할 방지 위해 모든 값을 " "로 감싸기)
df[["SMS","clean_df"]].to_csv("data30_preprocessing.csv", index=False, encoding="utf-8-sig", quoting=csv.QUOTE_ALL)